### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by kmchord9** [kmchord9/docker-vue#1]
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1588554678764-0.7983480303522339/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> chartjs@1.0.0 dev /code
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 94% asset optimization                                                              

 ERROR  Failed to compile with 1 errors                                                                                                                            1:11:20 AM

Module build failed: Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/code/node_modules/eslint/lib/config.js:255:39)
    at Config.getConfigHierarchy (/code/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/code/node_modules/eslint/lib/config.js:286:21)
    at Config.getConfig (/code/node_modules/eslint/lib/config.js:329:29)
    at processText (/code/node_modules/eslint/lib/cli-engine.js:163:33)
    at CLIEngine.executeOnText (/code/node_modules/eslint/lib/cli-engine.js:620:17)
    at lint (/code/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/code/node_modules/eslint-loader/index.js:213:21)

**Comment by kmchord9** [comment]
https://github.com/webpack-contrib/eslint-loader/issues/209

https://eslint.org/docs/user-guide/getting-started

**Comment by kmchord9** [comment]
yarn global add webpack-cli
